/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient */

#ifndef _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
#define _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_init
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    generatePartialPublicKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_generatePartialPublicKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    setPublicKey
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_setPublicKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    encrypt
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_encrypt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    partiallyDecrypt
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_partiallyDecrypt
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
