/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer */

#ifndef _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
#define _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_init
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    accumulatePartialPublicKeys
 * Signature: ([[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_accumulatePartialPublicKeys
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    accumulateCiphertexts
 * Signature: ([[J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_accumulateCiphertexts
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    averageBlocks
 * Signature: ([J[[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_averageBlocks
  (JNIEnv *, jobject, jlongArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
