/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer */

#ifndef _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
#define _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_init
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    generateA
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_generateA
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    aggregatePartialPublicKeys
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_aggregatePartialPublicKeys
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    accumulateCiphertexts
 * Signature: ([Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_accumulateCiphertexts
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer
 * Method:    average
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALServer_average
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
