/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient */

#ifndef _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
#define _Included_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_init
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    generatePartialPublicKey
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_generatePartialPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    setPublicKey
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_setPublicKey
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    encryptBlock
 * Signature: ([D)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_encryptBlock
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient
 * Method:    partiallyDecryptBlock
 * Signature: ([J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_apache_sysds_runtime_controlprogram_paramserv_homomorphicEncryption_SEALClient_partiallyDecryptBlock
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
